apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: prod-issuer
  namespace: cert-manager
spec:
  acme:
    email: certs@mineblow.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: certs-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: ethan.roberts@mineblow.com
          apiTokenSecretRef:
            name: cloudflare-secret
            key: api-token
