apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm  # Official Helm Chart Repo
      targetRevision: 7.8.5
      helm:
        installCRDS:
          - true  # This tells ArgoCD to pull values from the Git source below


  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  # ignoreDifferences:
  #   - group: apps
  #     kind: Deployment
  #     jsonPointers:
  #       - /spec/selector